export const data = [
  {
    id: 1,
    name: "Firefly",
    img: "https://static.wikia.nocookie.net/avatar/images/1/13/Fireflies.png/revision/latest?cb=20140118124601",
    location: "Northern Air Temple",
  },
  {
    id: 2,
    name: "Flying Bison",
    img: "https://static.wikia.nocookie.net/avatar/images/b/be/Appa%27s_mother.png/revision/latest/scale-to-width-down/200?cb=20130705194428",
    location: "Any Air Temple",
  },
  {
    id: 3,
    name: "Hermit crab",
    img: "https://static.wikia.nocookie.net/avatar/images/a/ac/Hermit_crab.png/revision/latest?cb=20140118124601",
    location: "Northern Air Temple",
  },
  {
    id: 4,
    name: "Ring Tailed Winged Lemur",
    img: "https://static.wikia.nocookie.net/avatar/images/f/f3/Ring-tailed_winged_lemur.png/revision/latest?cb=20150627131941",
    location: "Air Temple Island",
  },
  {
    id: 5,
    name: "Winged Lemur",
    img: "https://static.wikia.nocookie.net/avatar/images/6/67/Winged_lemur.png/revision/latest?cb=20140108092622",
    location: "Any Air Temple",
  },
  {
    id: 6,
    name: "Otter Penguin",
    img: "https://static.wikia.nocookie.net/avatar/images/d/db/Otter_penguin_colony.png/revision/latest?cb=20140102150506",
    location: "South Pole Region",
  },
  {
    id: 7,
    name: "Tiger Seal",
    img: "https://static.wikia.nocookie.net/avatar/images/9/99/Tiger_seal.png/revision/latest?cb=20150813142910",
    location: "South Pole Region",
  },
  {
    id: 8,
    name: "Turtle Seal",
    img: "https://imgs.search.brave.com/rRTokHJtgZe0-j2RG8xv3Lzcxl6teIcpnLQAIymI924/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzL2FmL2Yz/LzFkL2FmZjMxZGIw/M2FkMjE1OTU4Mzky/YmMzZDdkZGU2YzA5/LmpwZw",
    location: "North Pole Region",
  },
  {
    id: 9,
    name: "Buffalo Yak",
    img: "https://static.wikia.nocookie.net/avatar/images/0/0a/Buffalo_yak.png/revision/latest?cb=20140119112247",
    location: "North Pole Region",
  },
  {
    id: 10,
    name: "Polar Dog",
    img: "https://static.wikia.nocookie.net/avatar/images/0/0a/Polar_dog.png/revision/latest?cb=20140102142541",
    location: "South Pole Region",
  },
  {
    id: 11,
    name: "Eel Hound",
    img: "https://imgs.search.brave.com/xV77m4LgZNJuEpw9d2owz5IUc6QWTGZxvlyGXhBApLA/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzL2FmLzE1/LzZjL2FmMTU2Yzk2/OGY3NGMyZGJjMjgx/YzkwZDNmNTFkYmFh/LmpwZw",
    location: "Earth Kingdom",
  },
  {
    id: 12,
    name: "Elephant Koi",
    img: "https://static.wikia.nocookie.net/avatar/images/6/66/Koi.png/revision/latest?cb=20130819085013",
    location: "Kyoshi Island",
  },
  {
    id: 13,
    name: "Unagi",
    img: "https://static.wikia.nocookie.net/avatar/images/3/36/Unagi.png/revision/latest?cb=20130819100053",
    location: "Kyoshi Island and Earth Kingdom",
  },
  {
    id: 14,
    name: "Badgermole",
    img: "https://static.wikia.nocookie.net/avatar/images/0/0c/Badgermoles.png/revision/latest/scale-to-width-down/350?cb=20150406222922",
    location: "Earth Kingdom",
  },
  {
    id: 15,
    name: "Goat Gorilla",
    img: "https://static.wikia.nocookie.net/avatar/images/4/4c/Goat_gorilla.png/revision/latest?cb=20130706150318",
    location: "Earth Kingdom",
  },
  {
    id: 16,
    name: "Turtle Duck",
    img: "https://imgs.search.brave.com/wPnn4NHmuLXqn0PmvN2PeR0FW1RUXF5Nh1gYNaKt6dA/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzLzBjLzRh/L2Y0LzBjNGFmNDI3/MWI5MzhmMmNhNzAx/YzEzMjg1ZTg1NTI2/LmpwZw",
    location: "Fire Nation",
  },
  {
    id: 17,
    name: "Dragon",
    img: "https://imgs.search.brave.com/aEJHGCLHeTEITPBqD6bQIpAykMfDVJQ0Bfo_DRAiu4A/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMud2lraWEubm9j/b29raWUubmV0L2F2/YXRhci9pbWFnZXMv/Yy9jNy9EcmFnb24u/cG5nL3JldmlzaW9u/L2xhdGVzdC9zY2Fs/ZS10by13aWR0aC1k/b3duLzIwMD9jYj0y/MDEzMDExODA4MjM1/MA",
    location: "Fire Nation",
  },
  {
    id: 18,
    name: "Messenger Hawk",
    img: "https://imgs.search.brave.com/hjdeaGVu3DatCleV6UpUuYgtflZV2ojqduDzJR_jNIE/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9wcmV2/aWV3LnJlZGQuaXQv/bnNsOTliNmM1YjA1/MS5qcGc_YXV0bz13/ZWJwJnM9MDlkZGMz/N2ZiZGI0MjU3NjUz/ZmVlMDYyOTc1ZWE1/YjhjMThjN2ZkNQ",
    location: "Fire Nation",
  },
  {
    id: 19,
    name: "Komodo Rhino",
    img: "https://static.wikia.nocookie.net/avatar/images/b/be/Komodo_rhino_at_the_North_Pole.png/revision/latest?cb=20140124171519",
    location: "Fire Nation",
  },
  {
    id: 20,
    name: "Puma Goat",
    img: "https://static.wikia.nocookie.net/avatar/images/9/94/Puma_goat.png/revision/latest?cb=20130613134752",
    location: "Fire Nation",
  },
];
